package com.nxsystems.nxpay.wallet.model.iface;
import com.nxsystems.nxpay.wallet.model.Client;


/** 
 * Object interface mapping for hibernate-handled table: account.
 * @author autogenerated
 */

public interface IAccount {



    /**
     * Return the value associated with the column: balance.
	 * @return A java.math.BigDecimal object (this.balance)
	 */
	java.math.BigDecimal getBalance();
	

  
    /**  
     * Set the value related to the column: balance.
	 * @param balance the balance value you wish to set
	 */
	void setBalance(final java.math.BigDecimal balance);

    /**
     * Return the value associated with the column: client.
	 * @return A Client object (this.client)
	 */
	Client getClient();
	

  
    /**  
     * Set the value related to the column: client.
	 * @param client the client value you wish to set
	 */
	void setClient(final Client client);

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: number.
	 * @return A String object (this.number)
	 */
	String getNumber();
	

  
    /**  
     * Set the value related to the column: number.
	 * @param number the number value you wish to set
	 */
	void setNumber(final String number);

	// end of interface
}