package com.nxsystems.nxpay.wallet.model.iface;
import com.nxsystems.nxpay.wallet.model.Client;
import java.util.Set;


/** 
 * Object interface mapping for hibernate-handled table: role.
 * @author autogenerated
 */

public interface IRole {



    /**
     * Return the value associated with the column: client.
	 * @return A Set&lt;Client&gt; object (this.client)
	 */
	Set<Client> getClients();
	
	/**
	 * Adds a bi-directional link of type Client to the set.
	 * @param client item to add
	 */
	void addClient(Client client);

  
    /**  
     * Set the value related to the column: client.
	 * @param client the client value you wish to set
	 */
	void setClients(final Set<Client> client);

    /**
     * Return the value associated with the column: description.
	 * @return A String object (this.description)
	 */
	String getDescription();
	

  
    /**  
     * Set the value related to the column: description.
	 * @param description the description value you wish to set
	 */
	void setDescription(final String description);

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	String getName();
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	void setName(final String name);

	// end of interface
}